ALTER TABLE job ADD COLUMN `is_deleted` bit(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER `ram_requirement`;
ALTER TABLE job ADD INDEX `idx_plan`(`plan_id`, `is_deleted`) USING BTREE;
ALTER TABLE plan ADD COLUMN `is_enabled` bit(1) NOT NULL DEFAULT 0 COMMENT '是否启动' AFTER `schedule_cron`;

CREATE TABLE plan_instance
(
    serial_id BIGINT AUTO_INCREMENT COMMENT '自增ID' PRIMARY KEY,
    plan_instance_id VARCHAR(64) NOT NULL COMMENT '计划实例ID',
    plan_id VARCHAR(64) NOT NULL COMMENT '计划ID',
    state tinyint(1) NOT NULL COMMENT '状态',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
)
COMMENT '计划实例';

CREATE TABLE job_instance
(
    serial_id BIGINT AUTO_INCREMENT COMMENT '自增ID' PRIMARY KEY,
    job_instance_id VARCHAR(64) NOT NULL COMMENT '作业实例ID',
    job_id VARCHAR(64) NOT NULL COMMENT '作业ID',
    plan_id VARCHAR(64) NOT NULL COMMENT '计划ID',
    state tinyint(1) NOT NULL COMMENT '状态',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
)
COMMENT '作业实例';
