ALTER TABLE job ADD COLUMN `is_deleted` bit(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER `ram_requirement`;
ALTER TABLE job ADD INDEX `idx_plan`(`plan_id`, `is_deleted`) USING BTREE;


CREATE TABLE plan_instance
(
    serial_id BIGINT AUTO_INCREMENT COMMENT '自增ID' PRIMARY KEY,
    plan_id VARCHAR(64) NOT NULL COMMENT '计划ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
)
COMMENT '计划实例';

CREATE TABLE job_instance
(
    serial_id BIGINT AUTO_INCREMENT COMMENT '自增ID' PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL COMMENT '作业ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
)
COMMENT '作业实例';
