### 新增 plan
POST http://{{host}}:{{port}}/api/admin/v1/plan
Content-Type: application/json

{
  "planId": "abcdef",
  "planDesc": "test",
  "scheduleOption": {
    "scheduleType": 3,
    "scheduleDelay": 1,
    "scheduleInterval": 3,
    "scheduleStartAt": "2021-07-26 16:15:00"
  },
  "jobs": [
    {
      "jobId": "1",
      "childrenIds": ["3"],
      "dispatchOption": {
        "dispatchType": 2
      },
      "executorOption": {
        "name": "hello",
        "type": 1
      }
    },
    {
      "jobId": "2",
      "childrenIds": ["3"],
      "dispatchOption": {
        "dispatchType": 2
      },
      "executorOption": {
        "name": "hello",
        "type": 1
      }
    },
    {
      "jobId": "3",
      "childrenIds": ["4", 5],
      "dispatchOption": {
        "dispatchType": 2
      },
      "executorOption": {
        "name": "hello",
        "type": 1
      }
    },
    {
      "jobId": "4",
      "dispatchOption": {
        "dispatchType": 2
      },
      "executorOption": {
        "name": "hello",
        "type": 1
      }
    },
    {
      "jobId": "5",
      "dispatchOption": {
        "dispatchType": 2
      },
      "executorOption": {
        "name": "hello",
        "type": 1
      }
    }
  ]
}

### 开启 plan
PUT http://{{host}}:{{port}}/api/admin/v1/plan/abcdef/start
Content-Type: application/json

### 停止 plan
PUT http://{{host}}:{{port}}/api/admin/v1/plan/abcdef/stop
Content-Type: application/json

