### 新增 plan
POST http://{{host}}:{{port}}/api/admin/v1/plan
Content-Type: application/json

{
  "planId": "abcdef",
  "planDesc": "test",
  "scheduleOption": {
    "scheduleType": 1,
    "scheduleStartAt": "2021-07-26 16:15:00"
  },
  "jobs": [
    {
      "jobId": "1",
      "jobDesc": "test",
      "dispatchOption": {
        "dispatchType": 2
      },
      "executor": {
        "name": "count",
        "type": 1
      }
    }
  ]
}

### 开启 plan
PUT http://{{host}}:{{port}}/api/admin/v1/plan/abcdef/enable
Content-Type: application/json

