### 新增 plan
POST http://{{host}}:{{port}}/api/v1/plan
Content-Type: application/json

{
    "description": "round_robin",
    "triggerType": 2,
    "planType": 2,
    "scheduleOption": {
        "scheduleType": 1,
        "scheduleDelay": 1,
        "scheduleInterval": 3,
        "scheduleStartAt": "2021-07-26 16:15:00"
    },
    "jobs": [
        {
            "name": "round_robin_job1",
            "description": "test",
            "type": 1,
            "triggerType": 2,
            "dispatchOption": {
                "loadBalanceType": 2
            },
            "executorName": "hello"
        }
    ]
}

### 替换 plan
PUT http://{{host}}:{{port}}/api/v1/plan/100001
Content-Type: application/json

{
    "description": "round_robin",
    "triggerType": 2,
    "planType": 2,
    "scheduleOption": {
        "scheduleType": 2,
        "scheduleDelay": 1,
        "scheduleInterval": 60,
        "scheduleStartAt": "2021-07-26 16:15:00"
    },
    "jobs": [
        {
            "name": "round_robin_job1",
            "description": "test",
            "type": 1,
            "triggerType": 2,
            "dispatchOption": {
                "loadBalanceType": 2
            },
            "executorName": "hello"
        }
    ]
}

### 开启 plan
PUT http://{{host}}:{{port}}/api/v1/plan/100001/start
Content-Type: application/json

### 停止 plan
PUT http://{{host}}:{{port}}/api/v1/plan/100001/stop
Content-Type: application/json

